version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Starting build...
      - echo "{\"apiKey\":\"${API_KEY}\"}" > config.json
      - mkdir -p dist
      - cp *.html *.css *.js *.json dist/ 2>/dev/null || true
      - cp -R deployment dist/ 2>/dev/null || true
      - cp -R scripts dist/ 2>/dev/null || true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*' 