version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Building static site"
      - echo '{"apiKey":"$API_KEY"}' > dashboard/config.json
      - mkdir -p dist
      - cp -R dashboard/* dist/
artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*' 