service: lead-management-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    VENDORS_TABLE: Vendors
    LEADS_TABLE: Leads
    USER_POOL_ID: us-east-1_lhc964tLD
    # Add DocuSign environment variables
    DS_INTEGRATION_KEY: ${ssm:/docusign/integration_key~true}
    DS_SECRET_KEY: ${ssm:/docusign/secret_key~true}
    DS_ACCOUNT_ID: ${ssm:/docusign/account_id~true}
    DS_USER_ID: ${ssm:/docusign/user_id~true}
    DS_RETAINER_TEMPLATE_ID: ${ssm:/docusign/retainer_template_id~true}
    DS_PRIVATE_KEY: ${ssm:/docusign/private_key~true}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.VENDORS_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.LEADS_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.LEADS_TABLE}/index/*"
    # Add SSM permissions for DocuSign
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource: 
        - "arn:aws:ssm:${self:provider.region}:*:parameter/docusign/*"
    # Add CloudWatch logs permissions
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:${self:provider.region}:*:*
    # Add Cognito ListUsers permission for email-to-username lookup
    - Effect: Allow
      Action:
        - cognito-idp:ListUsers
        - cognito-idp:ForgotPassword
        - cognito-idp:ConfirmForgotPassword
      Resource: "arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:provider.environment.USER_POOL_ID}"
  # Configure API Gateway access logs
  apiGateway:
    restApiId: !Ref ApiGateway
    metrics: true
    usagePlan:
      - apiKeys:
          - name: leads-api-key
            description: API key for leads management
        throttle:
          burstLimit: 10
          rateLimit: 5
    # Enable logging to CloudWatch
    accessLogging: true
    executionLogging: true
    dataTracing: true

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /leads
          method: post
          cors: true
          private: true # Require API key
      - http:
          path: /leads
          method: get
          cors: true
      # Adding lead update endpoint
      - http:
          path: /leads/{lead_id}
          method: patch
          cors: true
          private: true # Require API key
      # Adding single lead GET endpoint
      - http:
          path: /leads/{lead_id}
          method: get
          cors: true
      # DocuSign Retainer Sending
      - http:
          path: /leads/{lead_id}/send-retainer
          method: post
          cors: true
          private: true # Require API key
      # DocuSign Webhook (Connect) endpoint
      - http:
          path: /docusign/webhook
          method: post
          cors: true
      # Adding Vendor Endpoints
      - http:
          path: /vendors
          method: get
          cors: true
      - http:
          path: /vendors
          method: post
          cors: true
          private: true # Require API key
      - http:
          path: /vendors/{vendor_code}/regenerate-key
          method: post
          cors: true
          private: true # Require API key
      # Admin force logout all users endpoint
      - http:
          path: /admin/force-logout-all
          method: post
          cors: true
      - http:
          path: /admin/force-logout-all
          method: options
          cors: true
  
  # New function to lookup username by email
  getUsernameByEmail:
    handler: get-username-by-email.handler
    events:
      - http:
          path: /get-username-by-email
          method: post
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: /get-username-by-email
          method: options
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
  
  # New function to handle forgot password requests
  forgotPassword:
    handler: forgot-password-handler.handler
    events:
      - http:
          path: /forgot-password
          method: post
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: /forgot-password
          method: options
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
            
  # New function to handle password reset confirmation
  confirmReset:
    handler: confirm-reset-handler.handler
    events:
      - http:
          path: /confirm-forgot-password
          method: post
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: /confirm-forgot-password
          method: options
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
  
  # For backward compatibility with existing code
  confirmForgotPassword:
    handler: confirm-forgot-password.handler
    events:
      - http:
          path: /auth/confirm-forgot-password
          method: post
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: /auth/confirm-forgot-password
          method: options
          cors:
            origin: 'https://main.d21xta9fg9b6w.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

resources:
  Resources:
    VendorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VENDORS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: vendor_code
            AttributeType: S
        KeySchema:
          - AttributeName: vendor_code
            KeyType: HASH
    
    LeadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.LEADS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: lead_id
            AttributeType: S
          - AttributeName: vendor_code
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: phone_home
            AttributeType: S
          - AttributeName: envelope_id
            AttributeType: S
        KeySchema:
          - AttributeName: lead_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: VendorTimestampIndex
            KeySchema:
              - AttributeName: vendor_code
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: PhoneIndex
            KeySchema:
              - AttributeName: phone_home
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: EnvelopeIdIndex
            KeySchema:
              - AttributeName: envelope_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    
    # Define API Gateway resource
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: leads-api
        Description: REST API for lead management
        EndpointConfiguration:
          Types:
            - REGIONAL
            
    # CloudWatch Log Group
    ApiGatewayLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/apigateway/leads-api
        RetentionInDays: 7 