AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for the Users DynamoDB table'

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: reset_token
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: ResetTokenIndex
          KeySchema:
            - AttributeName: reset_token
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Application
          Value: CRM
        - Key: Environment
          Value: Production

Outputs:
  UsersTableName:
    Description: Name of the Users DynamoDB table
    Value: !Ref UsersTable
  UsersTableArn:
    Description: ARN of the Users DynamoDB table
    Value: !GetAtt UsersTable.Arn 